name: "Template sync dispatcher"
on:
  workflow_call:
    inputs:
      SOURCE_REPO_NAME:
        required: true
        type: string
      REF_NAME:
        required: true
        type: string
    secrets:
      GH_ACCESS_TOKEN:
        description: "A token passed from the caller workflow"
        required: true
env:
  GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

jobs:
  get-inheritance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
      - id: search-inheritance
        uses: sonergia/github-reusable-workflows/.github/actions/search-inheritance@2.x
        with:
          REPO_NAME: ${{ inputs.SOURCE_REPO_NAME }}
          ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
    outputs:
      ALL: ${{ steps.search-inheritance.outputs.ALL }}

  dispatcher:
    # Run only on non empty matrix (no "length" function here)
    if: fromJSON(needs.get-inheritance.outputs.ALL)[0] != null
    runs-on: ubuntu-latest
    needs:
      - get-inheritance
    strategy:
      matrix:
        repo_name: ${{ fromJSON(needs.get-inheritance.outputs.ALL) }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
      - name: Get default branch from origin of Sonergia/${{ matrix.repo_name }}
        id: get-origin-default-branch
        run: |
          echo "DEFAULT_BRANCH=$(
            gh repo view Sonergia/${{ matrix.repo_name }} \
              --json defaultBranchRef \
              --jq '.defaultBranchRef.name'
          )" >> ${GITHUB_OUTPUT}

      - name: Invoke template-sync workflow on ${{ matrix.repo_name }}
        uses: benc-uk/workflow-dispatch@v1.2.2
        with:
          workflow: template-sync.yml
          repo: Sonergia/${{ matrix.repo_name }}
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          ref: ${{ steps.get-origin-default-branch.outputs.default_branch }}
          inputs: '{ "REF_NAME": "${{ inputs.REF_NAME }}" }'
